// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPKovanIEvWa3oQtU3WP4jq8BMLKEzRg',
    appId: '1:500769062162:web:8c7933c946f0cf331247cb',
    messagingSenderId: '500769062162',
    projectId: 'wydaccounts',
    authDomain: 'wydaccounts.firebaseapp.com',
    storageBucket: 'wydaccounts.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSab3eAr9yqlsrBLPPc1rd6u2cwsORVWs',
    appId: '1:500769062162:android:c2fdbf6675d200191247cb',
    messagingSenderId: '500769062162',
    projectId: 'wydaccounts',
    storageBucket: 'wydaccounts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhCvq61wLtRh0n1g5fnDt4RhMkLDDKABQ',
    appId: '1:500769062162:ios:adea9cef64a12a6d1247cb',
    messagingSenderId: '500769062162',
    projectId: 'wydaccounts',
    storageBucket: 'wydaccounts.appspot.com',
    iosBundleId: 'com.example.wydFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhCvq61wLtRh0n1g5fnDt4RhMkLDDKABQ',
    appId: '1:500769062162:ios:adea9cef64a12a6d1247cb',
    messagingSenderId: '500769062162',
    projectId: 'wydaccounts',
    storageBucket: 'wydaccounts.appspot.com',
    iosBundleId: 'com.example.wydFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUPKovanIEvWa3oQtU3WP4jq8BMLKEzRg',
    appId: '1:500769062162:web:86740fb1914ee4501247cb',
    messagingSenderId: '500769062162',
    projectId: 'wydaccounts',
    authDomain: 'wydaccounts.firebaseapp.com',
    storageBucket: 'wydaccounts.appspot.com',
  );

}