// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIzyaxlq1U8-apptQMadgbZbjAWX2cqUA',
    appId: '1:757643281393:web:445561e294bbcec366fa50',
    messagingSenderId: '757643281393',
    projectId: 'wyddevelop',
    authDomain: 'wyddevelop.firebaseapp.com',
    storageBucket: 'wyddevelop.firebasestorage.app',
    measurementId: 'G-HF9MQM7CHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1pE_u4oXjEnJVE0D0x0d4eafcIUCQs0',
    appId: '1:757643281393:android:0c91e013f288afe766fa50',
    messagingSenderId: '757643281393',
    projectId: 'wyddevelop',
    storageBucket: 'wyddevelop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwgpilqYzMYlhhaZ640BLzfdJUuzHO_qQ',
    appId: '1:757643281393:ios:08dd90204de45db066fa50',
    messagingSenderId: '757643281393',
    projectId: 'wyddevelop',
    storageBucket: 'wyddevelop.firebasestorage.app',
    iosBundleId: 'com.example.wydFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwgpilqYzMYlhhaZ640BLzfdJUuzHO_qQ',
    appId: '1:757643281393:ios:08dd90204de45db066fa50',
    messagingSenderId: '757643281393',
    projectId: 'wyddevelop',
    storageBucket: 'wyddevelop.firebasestorage.app',
    iosBundleId: 'com.example.wydFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIzyaxlq1U8-apptQMadgbZbjAWX2cqUA',
    appId: '1:757643281393:web:2c94536ff5199cae66fa50',
    messagingSenderId: '757643281393',
    projectId: 'wyddevelop',
    authDomain: 'wyddevelop.firebaseapp.com',
    storageBucket: 'wyddevelop.firebasestorage.app',
    measurementId: 'G-H8HB7WE0FF',
  );
}
